- name: Build custom Docker image from Dockerfile 
  community.docker.docker_image:
    name: "{{ image }}"
    tag: "{{ image_tag }}"
    build:
      path: "{{ docker_build_dir }}"
      pull: true
    source: build
    state: present

- name: Run container from the custom built image
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ image }}:{{ image_tag }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ host_port }}:{{ container_port }}"
      
