aws_banner: |
  =======================================
  AWS Instance Specifications
  =======================================
  Name Tag:          ohio-cloud1
  Region:            us-east-2
  Instance Type:     t3.micro
  AMI ID:            ami-0e5497a77ef21b5ac
  Key Pair:          ohio-cloud2
  VPC ID:            vpc-060011518b8efd6d0
  Subnet ID:         subnet-09b623c5ccf8ea008
  Security Group ID: sg-05449ab83315bac90
  Elastic IP Alloc:  eipalloc-075b6eef33e25da93
  =======================================
