- name: General Infra Setup
  ansible.builtin.include_tasks: setup.yml 

- name: Loop over required services
  ansible.builtin.include_tasks: manage-service.yml
  loop: "{{ app_services }}"
  loop_control:
    loop_var: service

- name: Compose Deployement
  ansible.builtin.include_tasks: compose.yml


