- name: Clean up decrypted Key
  ansible.builtin.file:
    path: "/tmp/{{ item }}.pem"
    state: absent
  delegate_to: localhost
  become: false
  loop: "{{ groups['all'] }}"
  loop_control:
    label: "{{ item }}"
