- name: Write SSH key from Vault
  copy:
    content: "{{ hostvars[item].vault_ssh_private_key }}"
    dest: "/tmp/{{ item }}.pem"
    mode: '0400'
  delegate_to: localhost
  become: false
  loop: "{{ groups['all'] }}"
  loop_control:
    label: "{{ item }}"
