- name: Create apt keyrings directory with correct permissions
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Download Docker official GPG KEY
  become: yes
  ansible.builtin.shell: >
    curl -4 --connect-timeout 15 --max-time 60 -fsSL
    https://download.docker.com/linux/ubuntu/gpg
    -o /etc/apt/keyrings/docker.asc
  args:
    creates: /etc/apt/keyrings/docker.asc

- name: Verify GPG key
  ansible.builtin.command: gpg --show-keys /etc/apt/keyrings/docker.asc
  changed_when: false
  register: gpg_check

- name: Set File Permissions
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    state: file
    mode: 'a+r'
  become: true

- name: Set the stable docker repository
  ansible.builtin.apt_repository: 
    state: present
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    update_cache: yes
  become: true

- name: Install the docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Ensure docker group exists
  ansible.builtin.user:
      name: "{{ target_user }}"
      groups: docker
      append: true


- name: Reset connection to apply group changes
  ansible.builtin.meta: reset_connection

- name: Verify Docker works with no sudo
  ansible.builtin.command: docker ps
  become: false



