- name: Install tree
  apt:
      name: tree
      state: present
      update_cache: yes

- name: Install curl
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Generate dynamic MOTD configuration
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
