app_name: cloud-1

compose_path: ../templates/docker-compose.yml.j2

build_dir: /opt/compose

target_mariadb_path: /opt/compose/mariadb
target_phpmyadmin_path: /opt/compose/phpmyadmin_container

network_name: wp_network

controller_path: ../files/

mariadb_container: mariadb
mariadb_image: mariadb
mariadb_host_port: 3306
mariadb_container_port: 3306

phpmyadmin_container: phpmyadmin
wordpress_container: wp
nginx_container: nginx

mariadb_volume: mariadb_data
wordpress_volume: wordpress_data

WP_SITE_TITLE: "cloud-1"

app_services:
  - name: "{{ mariadb_container }}"
    target_path: "{{ build_dir }}/{{ mariadb_container }}"
    src_path: "{{ controller_path }}/{{ mariadb_container }}"
    files:
      - custom.cnf
      - Dockerfile
      - entrypoint.sh

  - name: "{{ wordpress_container }}"
    target_path: "{{ build_dir }}/{{ wordpress_container }}"
    src_path: "{{ controller_path }}/{{ wordpress_container }}"
    files:
      - entrypoint.sh
      - Dockerfile

  - name: "{{ nginx_container }}"
    target_path: "{{ build_dir }}/{{ nginx_container }}"
    src_path: "{{ controller_path }}/{{ nginx_container }}"
    files:
      - Dockerfile
      - entrypoint.sh
      - nginx.conf

  - name: "{{ phpmyadmin_container }}"
    target_path: "{{ build_dir }}/{{ phpmyadmin_container }}"
    src_path: "{{ controller_path }}/{{ phpmyadmin_container }}"
    files:
      - Dockerfile
      - init.sh
