- name: Local setup (banner, SSH)
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - info
    - ssh

- name: Provision EC2 with Terraform
  hosts: all
  gather_facts: false
  connection: local
  roles:
    - terraform
