- name: Local setup (banner, SSH, Terraform)
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
    - vars/aws_specs.yml
  pre_tasks:
    - name: Print AWS Instance Specifications
      ansible.builtin.debug:
        msg: "{{ aws_banner.split('\n') }}"
  roles:
    - ssh
    - terraform
